APP_NAME = "YouTube Music Playlist Manager"
APP_VERSION = "0.2.0"
APP_BUNDLE_IDENTIFIER = "com.hruif.youtube-music-playlist-manager"
APP_REPOSITORY = "hruif/YouTubeMusicPlaylistManager"
APP_RELEASES_URL = f"https://github.com/{APP_REPOSITORY}/releases"
APP_RELEASES_API_URL = f"https://api.github.com/repos/{APP_REPOSITORY}/releases/latest"
PLAYER_WINDOW_ARG = "--youtube-player-window"
